default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_DEV_DATABASE'] %>
  username: <%= ENV['DB_DEV_USER'] %>
  password: <%= ENV['DB_DEV_PASSWORD'] %>
  host: <%= ENV['DB_DEV_HOST'] %>
  port: <%= ENV['DB_DEV_PORT'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_DATABASE'] %>
  username: <%= ENV['DB_TEST_USER'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
  host: <%= ENV['DB_TEST_HOST'] %>
  port: <%= ENV['DB_TEST_PORT'] %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
